{% set name = "gperftools" %}
{% set version = "2.8" %}
{% set sha256 = "b09193adedcc679df2387042324d0d54b93d35d062ea9bff0340f342a709e860" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - make
    - libtool
    - {{ pin_compatible('libunwind', max_pin='x.x') }}  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libunwind  # [linux]
  run:
    - perl

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - pprof --help

about:
  home: http://github.com/gperftools/gperftools
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: The fastest malloc we have seen; works particularly well with threads and STL
  description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
  doc_url: https://github.com/gperftools/gperftools/wiki
  dev_url: https://github.com/gperftools/gperftools

extra:
  recipe-maintainers:
    - xmnlab
