{% set name = "gperftools" %}
{% set version = "2.17.2" %}
{% set sha256 = "bb172a54312f623b53d8b94cab040248c559decdb87574ed873e80b516e6e8eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gperftools/gperftools/releases/download/gperftools-{{ version }}/gperftools-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ pin_compatible('libunwind', max_pin='x.x') }}  # [linux]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - gnuconfig  # [unix]
  host:
    - libunwind  # [linux]
  run:
    - perl

test:
  commands:
    - test -f $PREFIX/lib/libtcmalloc$SHLIB_EXT

about:
  home: https://github.com/gperftools/gperftools
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: The fastest malloc we have seen; works particularly well with threads and STL
  description: |
    gperftools is a collection of a high-performance multi-threaded
    malloc() implementation, plus some pretty nifty performance analysis
    tools.
  doc_url: https://github.com/gperftools/gperftools/wiki
  dev_url: https://github.com/gperftools/gperftools

extra:
  recipe-maintainers:
    - xmnlab
    - matthiasdiener
