appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PWeIkwvRLcTLbS5K69KmfdlnFzvGlCgquDGd8zbLqubvbDSXorcPZWnxH+NFjso+7l9xuWCC9wmQ4ExaK2Vr6SdySd18Q515GzMczqNB12F4S96xtji0nhMX8R5zK7JgDVT3JxN2kjO3b2ogzzyIRnsvRgFMne77vMTovwCUMgkMGOEO8ylx670XE+ecPfqqw1uVOXXZv+AWBnz8GX5Trw/ur13sohevOvkuEe0MJ/qtm3K8VQK7BS3V6scONFs/3tNcGFk7uPRV3Va+CkWbzlLSZVZxtP+Kz0+tkz8g3x0Xh0yiSN1CDgu0H3D9TP2A/LVP02t+WSzeZrpQFs3JU2PWMCC5ENxiIJl6V4yw6sq6y/vsekQXg4K7jW+k+smqejn49cUbUX1avDKufYDijQJC5+ZZB3IvptY8bZ8JZTIIpsG+dU9/fLvCbrgN80gROuII+A8A36m/pfAoyKFOJICEQCmvEIStmBLqUDHqhI+NfYyJQZOgps9E4a/BMZWLZgsNjNPWaY+AlSqqowFddB4tc+Zxd9NONxWsINTWEFywI/PalgaaxB6ySYtO5bQsszj/6cIaBa/qffnvZtj24QtxvMytTjEdY4+GSQUXwK0X5t/3UrHyOOgFNQZAWj5fuTCjFpeedt+lF/VL6fAffigmLVnez8ra4gi/AIgLF+0=}
